### ISSUE TITLE
Docs on JsonApiExceptions and Handler

### ISSUE THREAD

**Issue by tomasvanrijsse** [Intermax-Cloudsourcing/laravel-json-api#9]
How should the custom [Exception Handler](https://github.com/Intermax-Cloudsourcing/laravel-json-api/blob/master/src/JsonApi/Exceptions/Handler.php) be implemented?
If I use a JsonApiException, without changing the default exception handler, it shows up as an escaped JSON string.

**Comment by phoogkamer** [comment]
Add the Middleware `RenderJsonApiExceptions` to the route (or in your global middleware).

Docs would be nice.

**Comment by phoogkamer** [comment]
Was already in the docs.
